### ISSUE TITLE
Fails to convert .raw into .mzML

### ISSUE THREAD

**Issue by Progklui** [PedrioliLab/ReAdW#2]
Hi,

I am using ReAdW for converting Thermo .raw files to .mzXML which is working nicely. However, if I try converting into .mzML as instructed in the README.txt it stops working.

What am I doing wrong or is somebody else experiencing this error.

Greetings:)

**Comment by ppedrioli** [comment]
On Fri, Aug 3, 2018 at 5:25 PM Flo Klui <notifications@github.com> wrote:

> Hi,
>
Dear Flo,

Thanks for getting in touch.


> I am using ReAdW for converting Thermo .raw files to .mzXML which is
> working nicely. However, if I try converting into .mzML as instructed in
> the README.txt it stops working.
>
There is no support for conversion to mzML in ReAdW. Or is that a typo?

If you are instead trying to convert to centroid mzXML, would it be
possible for you to share:
1. The command you are using
2. The error you are getting (if any)
3. Which binary you are using (MSFileReader or Xcalibur based one)
4. The version of MSFileReader / Xcalibur you are using
5. The file you are trying to convert

Thanks.
Cheers,

 Patrick

What am I doing wrong or is somebody else experiencing this error.

**Comment by Progklui** [comment]
Hi,

converting to centroid .mzXML works just fine. I just experience problems with .mzML but if it isn't supported the problem is solved;).

Thank you very much. Florian
